name: Indexer QA Block Streaming Test (Preprod)

on:
  workflow_dispatch:
  schedule:
    # Every 10 minutes on workdays (Mon-Fri), covering UK and US working hours (07:00-21:00 UTC)
    - cron: '*/10 7-21 * * 1-5'

jobs:
  test-block-subscriptions:
    name: Test Block Subscriptions
    uses: ./.github/workflows/qa-test-block-subscription-base-workflow.yml
    with:
      target_env: preprod
      indexer_api_version: v3
